routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\DimensiController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\KuesionerController;
use App\Http\Controllers\PertanyaanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('pengguna', PenggunaController::class);
Route::resource('dimensi', DimensiController::class);
Route::resource('pertanyaan', PertanyaanController::class);

Route::get('/login', [LoginController::class, 'index'] );
Route::post('/login', [LoginController::class, 'authenticate'] );
Route::post('/logout', [LoginController::class, 'logout'] );

Route::get('/kuesioner', [KuesionerController::class, 'getAllKuesioner'] )->name('kuesioner.kuesioner');
Route::post('/store', [KuesionerController::class, 'store'] )->name('jawaban.store');

Route::get('/dashboard', [LoginController::class, 'afterLogin'] )->name('dashboard.dashboard');

app/Models/Dimensi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dimensi extends Model
{
    use HasFactory;
    protected $table = "tbdimensi";

}

app/Http/Controllers/DimensiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Dimensi;

class DimensiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = Dimensi::all();
        return view('dimensi.dimensi', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Dimensi;
        return view('dimensi.create', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, ['dimensi' => 'required',
    'bobot' => 'required']);
    $model = new Dimensi;
    $model -> dimensi = $request->dimensi;
    $model -> bobot = $request->bobot;
    $model->save();

    if($model){
        return redirect()
            ->route('dimensi.index')
            ->with([
                'success' => 'Berhasil Tambahkan Data'
            ]);
    }else{
        return redirect()
            ->back
            ->withInput()
            ->with([
                'error' => 'Gagal Tambahkan Data'
            ]);
    }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Dimensi::findOrFail($id);
        return view('dimensi.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, ['dimensi' => 'required',
        'bobot' => 'required']);
        $model = Dimensi::find($id);
        $model -> dimensi = $request->dimensi;
        $model -> bobot = $request->bobot;
        $model->save();

        if($model){
            return redirect()
                ->route('dimensi.index')
                ->with([
                    'success' => 'Berhasil Ubah Data'
                ]);
        }else{
            return redirect()
                ->back
                ->withInput()
                ->with([
                    'error' => 'Gagal Ubah Data'
                ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Dimensi::findOrFail($id);
        $model->delete();
        if($model){
            return redirect()
                ->route('dimensi.index')
                ->with([
                    'success' => 'Berhasil Hapus Data'
                ]);
        }else{
            return redirect()
                ->back
                ->withInput()
                ->with([
                    'error' => 'Gagal Hapus Data'
                ]);
        }
    }
}

resources/views/dimensi/create.blade.php
@extends('layouts.maindashboard')

@section('content')
<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <!-- Notifikasi menggunakan flash session data -->
                @if (session('success'))
                <div class="alert alert-success" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('success') }}</strong>
                </div>
                @endif

                @if (session('error'))
                <div class="alert alert-error" id="error-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('error') }}</strong>
                </div>
                @endif

                <div class="card border-0 shadow rounded">
                <div class="card-header">
                     <h1 class="card-title"><strong>Form Tambah Dimensi</strong></h1>
                    </div>
                    <div class="card-body">
                    
                        <form action="{{ route('dimensi.store') }}" method="POST">
                            @csrf
                            <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="dimensi">Nama Dimensi</label>
                                <input type="text" class="form-control @error('dimensi') is-invalid @enderror"
                                    name="dimensi" value="{{ old('dimensi') }}" required>

                                <!-- error message untuk title -->
                                @error('dimensi')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-6">
                                <label for="bobot">Bobot Dimensi</label>
                                <input type="number" class="form-control @error('bobot') is-invalid @enderror"
                                    name="bobot" value="{{ old('bobot') }}" required>

                                <!-- error message untuk title -->
                                @error('bobot')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            </div>
                            <button type="submit" class="btn btn-md btn-primary">Save</button>
                            <a href="{{ route('dimensi.index') }}" class="btn btn-md btn-secondary">Back</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <script>
        $(document).ready(function() {
  $("#success-alert").hide();
  $("#myWish").click(function showAlert() {
    $("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
      $("#success-alert").slideUp(500);
    });
  });
});
    </script> -->

    <script>
// setTimeout( myStopFunction, 2500);

// function myStopFunction() {
//  $('#success-alert').hide();
// }

$("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
    $("#success-alert").slideUp(500);
});
    </script>

@endsection

resources/views/dimensi/dimensi.blade.php
@extends('layouts.maindashboard')

@section('content')
<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <!-- Notifikasi menggunakan flash session data -->

                @if (session('success'))
                <div class="alert alert-success" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('success') }}</strong>
                </div>
                @endif

                @if (session('error'))
                <div class="alert alert-error" id="error-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('error') }}</strong>
                </div>
                @endif


                <div class="card border-0 shadow rounded">
                <div class="card-header">
                     <h1 class="card-title"><strong>Data Dimensi</strong></h1>
                </div>
                    <div class="card-body">
                        <a href="{{url('dimensi/create')}}" class="btn btn-md btn-success mb-3 float-right">Tambah Data</a>

                        <table id="role_table" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th scope="col">No</th>
                                    <th scope="col">Dimensi</th>
                                    <th scope="col">Bobot</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($datas as $key=> $data)
                                <tr>
                                    <td>{{ ++$key }}</td>
                                    <td>{{ $data->dimensi }}</td>
                                    <td>{{ $data->bobot }}</td>
                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                            action="{{ route('dimensi.destroy', $data->id) }}" method="POST">
                                            <a href="{{ route('dimensi.edit', $data->id) }}    "
                                                class="btn btn-sm btn-primary">Ubah</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">Hapus</button>
                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td class="text-center text-mute" colspan="4">Data post tidak tersedia</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


   

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script> -->

<script>
    $(document).ready(function() {
    $('#role_table').DataTable();
} );
</script>

<script>
// setTimeout( myStopFunction, 2500);

// function myStopFunction() {
//  $('#success-alert').hide();
// }

$("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
    $("#success-alert").slideUp(500);
});
    </script>

    <!-- <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 -->
@endsection

resources/views/dimensi/edit.blade.php
@extends('layouts.maindashboard')

@section('content')
<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <!-- Notifikasi menggunakan flash session data -->
                @if (session('success'))
                <div class="alert alert-success" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('success') }}</strong>
                </div>
                @endif

                @if (session('error'))
                <div class="alert alert-error" id="error-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('error') }}</strong>
                </div>
                @endif

                <div class="card border-0 shadow rounded">
                <div class="card-header">
                     <h1 class="card-title"><strong>Form Ubah Dimensi</strong></h1>
                    </div>
                    <div class="card-body">
                    
                        <form action="{{ route('dimensi.update', $model->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="dimensi">Nama Dimensi</label>
                                <input type="text" class="form-control @error('dimensi') is-invalid @enderror"
                                    name="dimensi" value="{{ old('dimensi', $model->dimensi) }}" required>

                                <!-- error message untuk title -->
                                @error('dimensi')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-6">
                                <label for="bobot">Bobot Dimensi</label>
                                <input type="number" class="form-control @error('bobot') is-invalid @enderror"
                                    name="bobot" value="{{ old('bobot', $model->bobot) }}" required>

                                <!-- error message untuk title -->
                                @error('bobot')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            </div>
                            <button type="submit" class="btn btn-md btn-primary">Save</button>
                            <a href="{{ route('dimensi.index') }}" class="btn btn-md btn-secondary">Back</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <script>
        $(document).ready(function() {
  $("#success-alert").hide();
  $("#myWish").click(function showAlert() {
    $("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
      $("#success-alert").slideUp(500);
    });
  });
});
    </script> -->

    <script>
// setTimeout( myStopFunction, 2500);

// function myStopFunction() {
//  $('#success-alert').hide();
// }

$("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
    $("#success-alert").slideUp(500);
});
    </script>

@endsection