routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\DimensiController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\KuesionerController;
use App\Http\Controllers\PertanyaanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('pengguna', PenggunaController::class);
Route::resource('dimensi', DimensiController::class);
Route::resource('pertanyaan', PertanyaanController::class);

Route::get('/login', [LoginController::class, 'index'] );
Route::post('/login', [LoginController::class, 'authenticate'] );
Route::post('/logout', [LoginController::class, 'logout'] );

Route::get('/kuesioner', [KuesionerController::class, 'getAllKuesioner'] )->name('kuesioner.kuesioner');
Route::post('/store', [KuesionerController::class, 'store'] )->name('jawaban.store');

Route::get('/dashboard', [LoginController::class, 'afterLogin'] )->name('dashboard.dashboard');

app/Models/Pengguna.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Pengguna extends Authenticatable
{
    use HasFactory;
    protected $table = "tbpengguna";

    protected $hidden = [
        'password'
    ];
}

app/Http/Controllers/PenggunaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Pengguna;

class PenggunaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = Pengguna::all();
        return view('pengguna.pengguna', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Pengguna;
        return view('pengguna.create', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, ['nama_pengguna' => 'required',
    'username' => 'required',
    'password' => 'required',
    'hak_akses' => 'required']);

    $model = new Pengguna;
    $model -> nama_pengguna = $request->nama_pengguna;
    $model -> username = $request->username;
    $model -> email = $request->email;
    $model -> password = bcrypt($request->password);
    $model -> handphone = $request->handphone;
    $model -> alamat = $request->alamat;
    $model -> hak_akses = $request->hak_akses;
    $model->save();

    if($model){
        return redirect()
            ->route('pengguna.index')
            ->with([
                'success' => 'Berhasil Tambahkan Data'
            ]);
    }else{
        return redirect()
            ->back
            ->withInput()
            ->with([
                'error' => 'Gagal Tambahkan Data'
            ]);
    }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Pengguna::findOrFail($id);
        return view('pengguna.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, ['nama_pengguna' => 'required',
        'username' => 'required',
        'hak_akses' => 'required']);

        $model = Pengguna::find($id);
        $model -> nama_pengguna = $request->nama_pengguna;
        $model -> username = $request->username;
        $model -> email = $request->email;
        $model -> handphone = $request->handphone;
        $model -> alamat = $request->alamat;
        $model -> hak_akses = $request->hak_akses;
        $model->save();
        
        if($model){
            return redirect()
                ->route('pengguna.index')
                ->with([
                    'success' => 'Berhasil Ubah Data'
                ]);
        }else{
            return redirect()
                ->back
                ->withInput()
                ->with([
                    'error' => 'Gagal Ubah Data'
                ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Pengguna::findOrFail($id);
        $model->delete();
        if($model){
            return redirect()
                ->route('pengguna.index')
                ->with([
                    'success' => 'Berhasil Hapus Data'
                ]);
        }else{
            return redirect()
                ->back
                ->withInput()
                ->with([
                    'error' => 'Gagal Hapus Data'
                ]);
        }
    }
}

resources/views/pengguna/create.blade.php
@extends('layouts.maindashboard')

@section('content')
<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <!-- Notifikasi menggunakan flash session data -->
                @if (session('success'))
                <div class="alert alert-success" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('success') }}</strong>
                </div>
                @endif

                @if (session('error'))
                <div class="alert alert-error" id="error-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('error') }}</strong>
                </div>
                @endif

                <div class="card border-0 shadow rounded">
                <div class="card-header">
                     <h1 class="card-title"><strong>Form Tambah Pengguna</strong></h1>
                    </div>
                    <div class="card-body">
                    
                        <form action="{{ route('pengguna.store') }}" method="POST">
                            @csrf
                            <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="nama_pengguna">Nama Pengguna</label>
                                <input type="text" class="form-control @error('nama_pengguna') is-invalid @enderror"
                                    name="nama_pengguna" value="{{ old('nama_pengguna') }}" required>

                                <!-- error message untuk title -->
                                @error('nama_pengguna')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-4">
                                <label for="username">Username</label>
                                <input type="text" class="form-control @error('username') is-invalid @enderror"
                                    name="username" value="{{ old('username') }}" required>

                                <!-- error message untuk title -->
                                @error('username')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-4">
                                <label for="password">Password</label>
                                <input type="password" class="form-control @error('password') is-invalid @enderror"
                                    name="password" value="{{ old('password') }}" required>

                                <!-- error message untuk title -->
                                @error('password')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-4">
                                <label for="email">Email</label>
                                <input type="text" class="form-control"
                                    name="email" value="{{ old('email') }}">
                            </div>

                            <div class="form-group col-md-4">
                            <label for="handphone">No. Handphone</label>
                                <input type="text" class="form-control"
                                    name="handphone" value="{{ old('handphone') }}" >
                            </div>

                            <div class="form-group col-md-4">
                            <label for="hak_akses">Hak Akses Pengguna</label>
                            <select id="hak_akses" class="form-control" name="hak_akses" value="{{ old('hak_akses') }}" required>
                                <option hidden>Pilih Hak Akses</option>
                                <option value="Administrator">Administrator</option>
                                <option value="Dekan">Dekan</option>=
                                <option value="Kepala Puskom">Kepala Puskom</option>
                                <option value="Kaprodi TI">Kaprodi TI</option>
                                <option value="Kaprodi SI">Kaprodi SI</option>
                            </select>
                            </div>

                            <div class="form-group col-md-8">
                            <label for="alamat">Alamat Tempat Tinggal</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" name="alamat" onKeyPress class="form-control" rows="3"> {{ old('alamat') }}</textarea>
                            </div>

                          

                            </div>
                            <button type="submit" class="btn btn-md btn-primary">Save</button>
                            <a href="{{ route('pengguna.index') }}" class="btn btn-md btn-secondary">Back</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <script>
        $(document).ready(function() {
  $("#success-alert").hide();
  $("#myWish").click(function showAlert() {
    $("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
      $("#success-alert").slideUp(500);
    });
  });
});
    </script> -->

    <script>
// setTimeout( myStopFunction, 2500);

// function myStopFunction() {
//  $('#success-alert').hide();
// }

$("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
    $("#success-alert").slideUp(500);
});
    </script>

@endsection

resources/views/pengguna/edit.blade.php
@extends('layouts.maindashboard')

@section('content')
<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <!-- Notifikasi menggunakan flash session data -->
                @if (session('success'))
                <div class="alert alert-success" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('success') }}</strong>
                </div>
                @endif

                @if (session('error'))
                <div class="alert alert-error" id="error-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('error') }}</strong>
                </div>
                @endif

                <div class="card border-0 shadow rounded">
                <div class="card-header">
                     <h1 class="card-title"><strong>Form Ubah Pengguna</strong></h1>
                    </div>
                    <div class="card-body">
                    
                        <form action="{{ route('pengguna.update', $model->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="nama_pengguna">Nama Pengguna</label>
                                <input type="text" class="form-control @error('nama_pengguna') is-invalid @enderror"
                                    name="nama_pengguna" value="{{ old('nama_pengguna', $model->nama_pengguna) }}" required>

                                <!-- error message untuk title -->
                                @error('nama_pengguna')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-4">
                                <label for="username">Username</label>
                                <input type="text" class="form-control @error('username') is-invalid @enderror"
                                    name="username" value="{{ old('username', $model->username) }}" required>

                                <!-- error message untuk title -->
                                @error('username')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-4">
                                <label for="password">Password</label>
                                <input type="password" class="form-control @error('password') is-invalid @enderror"
                                    name="password" value="{{ old('password', $model->password) }}" disabled>

                                <!-- error message untuk title -->
                                @error('password')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-4">
                                <label for="email">Email</label>
                                <input type="text" class="form-control"
                                    name="email" value="{{ old('email', $model->email) }}">
                            </div>

                            <div class="form-group col-md-4">
                            <label for="handphone">No. Handphone</label>
                                <input type="text" class="form-control"
                                    name="handphone" value="{{ old('handphone', $model->handphone) }}" >
                            </div>

                            <div class="form-group col-md-4">
                            <label for="hak_akses">Hak Akses Pengguna</label>
                            <select id="hak_akses" class="form-control" name="hak_akses" value="{{ old('hak_akses', $model->hak_akses) }}" required>
                                <option hidden>Pilih Hak Akses</option>
                                <option value="Administrator" {{$model->hak_akses == 'Administrator' ? 'selected': '' }}>Administrator</option>
                                <option value="Dekan" {{$model->hak_akses == 'Dekan' ? 'selected': '' }}>Dekan</option>
                                <option value="Kepala Puskom" {{$model->hak_akses == 'Kepala Puskom' ? 'selected': '' }}>Kepala Puskom</option>
                                <option value="Kaprodi TI" {{$model->hak_akses == 'Kaprodi TI' ? 'selected': '' }}>Kaprodi TI</option>
                                <option value="Kaprodi SI" {{$model->hak_akses == 'Kaprodi SI' ? 'selected': '' }}>Kaprodi SI</option>
                            </select>
                            </div>

                            <div class="form-group col-md-8">
                            <label for="alamat">Alamat Tempat Tinggal</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" name="alamat" onKeyPress class="form-control" rows="3"> {{ old('alamat') }}</textarea>
                            </div>

                          

                            </div>
                            <button type="submit" class="btn btn-md btn-primary">Save</button>
                            <a href="{{ route('pengguna.index') }}" class="btn btn-md btn-secondary">Back</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <script>
        $(document).ready(function() {
  $("#success-alert").hide();
  $("#myWish").click(function showAlert() {
    $("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
      $("#success-alert").slideUp(500);
    });
  });
});
    </script> -->

    <script>
// setTimeout( myStopFunction, 2500);

// function myStopFunction() {
//  $('#success-alert').hide();
// }

$("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
    $("#success-alert").slideUp(500);
});
    </script>

@endsection

resources/views/pengguna/pengguna.blade.php
@extends('layouts.maindashboard')

@section('content')
<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <!-- Notifikasi menggunakan flash session data -->

                @if (session('success'))
                <div class="alert alert-success" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('success') }}</strong>
                </div>
                @endif

                @if (session('error'))
                <div class="alert alert-error" id="error-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('error') }}</strong>
                </div>
                @endif


                <div class="card border-0 shadow rounded">
                <div class="card-header">
                     <h1 class="card-title"><strong>Data Pengguna</strong></h1>
                </div>
                    <div class="card-body">
                        <a href="{{url('pengguna/create')}}" class="btn btn-md btn-success mb-3 float-right">Tambah Data</a>

                        <table id="role_table" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th scope="col">Nama Pengguna</th>
                                    <th scope="col">Username</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">No. Handphone</th>
                                    <th scope="col">Hak Akses</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($datas as $data)
                                <tr>
                                    <td>{{ $data->nama_pengguna }}</td>
                                    <td>{{ $data->username }}</td>
                                    <td>{{ $data->email }}</td>
                                    <td>{{ $data->handphone }}</td>
                                    <td>{{ $data->hak_akses }}</td>
                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                            action="{{ route('pengguna.destroy', $data->id) }}" method="POST">
                                            <a href="{{ route('pengguna.edit', $data->id) }}    "
                                                class="btn btn-sm btn-primary">Ubah</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">Hapus</button>
                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td class="text-center text-mute" colspan="6">Data post tidak tersedia</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


   

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script> -->

<script>
    $(document).ready(function() {
    $('#role_table').DataTable();
} );
</script>

<script>
// setTimeout( myStopFunction, 2500);

// function myStopFunction() {
//  $('#success-alert').hide();
// }

$("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
    $("#success-alert").slideUp(500);
});
    </script>

    <!-- <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 -->
@endsection