routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\DimensiController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\KuesionerController;
use App\Http\Controllers\PertanyaanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('pengguna', PenggunaController::class);
Route::resource('dimensi', DimensiController::class);
Route::resource('pertanyaan', PertanyaanController::class);

Route::get('/login', [LoginController::class, 'index'] );
Route::post('/login', [LoginController::class, 'authenticate'] );
Route::post('/logout', [LoginController::class, 'logout'] );

Route::get('/kuesioner', [KuesionerController::class, 'getAllKuesioner'] )->name('kuesioner.kuesioner');
Route::post('/store', [KuesionerController::class, 'store'] )->name('jawaban.store');

Route::get('/dashboard', [LoginController::class, 'afterLogin'] )->name('dashboard.dashboard');

app/Models/Pertanyaans.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pertanyaans extends Model
{
    use HasFactory;
    protected $table = "tbkuesioner";
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Kuesioner;
use App\Models\Dimensi;

class PertanyaanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = DB::table('tbkuesioner')
        ->join('tbdimensi', 'tbkuesioner.id_dimensi', '=', 'tbdimensi.id')
        ->select('tbkuesioner.id', 'tbkuesioner.pertanyaan', 'tbkuesioner.pila', 'tbdimensi.dimensi',
         'tbkuesioner.pilb', 'tbkuesioner.pilc', 'tbkuesioner.pild', 'tbkuesioner.pile', 'tbkuesioner.variabel')
        ->get();
        return view('pertanyaan.pertanyaan', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Kuesioner;
        $dimensis = Dimensi::all();
        return view('pertanyaan.create', compact('model','dimensis'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, ['pertanyaan' => 'required',
        'id_dimensi' => 'required',
        'pila' => 'required',
        'pilb' => 'required',
        'pilc' => 'required',
        'pild' => 'required',
        'pile' => 'required']);

        $model = new Kuesioner;
        $model -> pertanyaan = $request->pertanyaan;
        $model -> id_dimensi = $request->id_dimensi;
        $model -> variabel = $request->variabel;
        $model -> pila = $request->pila;
        $model -> pilb = $request->pilb;
        $model -> pilc = $request->pilc;
        $model -> pild = $request->pild;
        $model -> pile = $request->pile;
        $model->save();

        if($model){
            return redirect()
                ->route('pertanyaan.index')
                ->with([
                    'success' => 'Berhasil Tambahkan Data'
                ]);
        }else{
            return redirect()
                ->back
                ->withInput()
                ->with([
                    'error' => 'Gagal Tambahkan Data'
                ]);
        }
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Kuesioner::findOrFail($id);
        $dimensis = Dimensi::all();
        return view('pertanyaan.edit', compact('model','dimensis'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, ['pertanyaan' => 'required',
        'id_dimensi' => 'required',
        'pila' => 'required',
        'pilb' => 'required',
        'pilc' => 'required',
        'pild' => 'required',
        'pile' => 'required']);

        $model = Kuesioner::find($id);
        $model -> pertanyaan = $request->pertanyaan;
        $model -> id_dimensi = $request->id_dimensi;
        $model -> variabel = $request->variabel;
        $model -> pila = $request->pila;
        $model -> pilb = $request->pilb;
        $model -> pilc = $request->pilc;
        $model -> pild = $request->pild;
        $model -> pile = $request->pile;
        $model->save();

        if($model){
            return redirect()
                ->route('pertanyaan.index')
                ->with([
                    'success' => 'Berhasil Ubah data'
                ]);
        }else{
            return redirect()
                ->back
                ->withInput()
                ->with([
                    'error' => 'Gagal Ubah data'
                ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Kuesioner::findOrFail($id);
        $model->delete();
        if($model){
            return redirect()
                ->route('pertanyaan.index')
                ->with([
                    'success' => 'Berhasil Hapus Data'
                ]);
        }else{
            return redirect()
                ->back
                ->withInput()
                ->with([
                    'error' => 'Gagal Hapus Data'
                ]);
        }
    }
}

app/Http/Controllers/PertanyaansController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PertanyaansController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pertanyaan/create.blade.php
@extends('layouts.maindashboard')

@section('content')
<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <!-- Notifikasi menggunakan flash session data -->
                @if (session('success'))
                <div class="alert alert-success" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('success') }}</strong>
                </div>
                @endif

                @if (session('error'))
                <div class="alert alert-error" id="error-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('error') }}</strong>
                </div>
                @endif

                <div class="card border-0 shadow rounded">
                <div class="card-header">
                     <h1 class="card-title"><strong>Form Tambah Pertanyaan</strong></h1>
                    </div>
                    <div class="card-body">
                    
                        <form action="{{ route('pertanyaan.store') }}" method="POST">
                            @csrf
                            <div class="form-row">
                            
                            <div class="form-group col-md-4">
                                <label for="pertanyaan">Pertanyaan</label>
                                <input type="text" class="form-control @error('pertanyaan') is-invalid @enderror"
                                    name="pertanyaan" value="{{ old('pertanyaan') }}" required>

                                <!-- error message untuk title -->
                                @error('pertanyaan')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-4">
                                <label for="variabel">Variabel</label>
                                <input type="text" class="form-control"
                                    name="variabel" value="{{ old('variabel') }}" >
                            </div>

                            <div class="form-group col-md-4">
                            <label for="id_dimensi">Dimensi</label>
                            <select id="id_dimensi" class="form-control @error('id_dimensi') is-invalid @enderror" name="id_dimensi" value="{{ old('id_dimensi') }}" required>
                                <option hidden>Pilih Dimensi</option>
                                @foreach ($dimensis as $dimensi)
                                <option value="{{$dimensi->id}}">{{$dimensi->dimensi}}</option>
                                @endforeach
                                
                            </select>
                            <!-- error message untuk title -->
                            @error('id_dimensi')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>


                            <div class="form-group col-md-12">
                                <label for="pila">Pilihan A</label>
                                <input type="text" class="form-control @error('pila') is-invalid @enderror"
                                    name="pila" value="{{ old('pila') }}" required>

                                <!-- error message untuk title -->
                                @error('pila')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-12">
                                <label for="pilb">Pilihan B</label>
                                <input type="text" class="form-control @error('pilb') is-invalid @enderror"
                                    name="pilb" value="{{ old('pilb') }}" required>

                                <!-- error message untuk title -->
                                @error('pilb')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-12">
                                <label for="pilc">Pilihan C</label>
                                <input type="text" class="form-control @error('pilc') is-invalid @enderror"
                                    name="pilc" value="{{ old('pilc') }}" required>

                                <!-- error message untuk title -->
                                @error('pilc')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-12">
                                <label for="pild">Pilihan D</label>
                                <input type="text" class="form-control @error('pild') is-invalid @enderror"
                                    name="pild" value="{{ old('pild') }}" required>

                                <!-- error message untuk title -->
                                @error('pild')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-12">
                                <label for="pile">Pilihan E</label>
                                <input type="text" class="form-control @error('pile') is-invalid @enderror"
                                    name="pile" value="{{ old('pile') }}" required>

                                <!-- error message untuk title -->
                                @error('pile')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>





                           

                            </div>
                            <button type="submit" class="btn btn-md btn-primary">Save</button>
                            <a href="{{ route('pertanyaan.index') }}" class="btn btn-md btn-secondary">Back</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <script>
        $(document).ready(function() {
  $("#success-alert").hide();
  $("#myWish").click(function showAlert() {
    $("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
      $("#success-alert").slideUp(500);
    });
  });
});
    </script> -->

    <script>
// setTimeout( myStopFunction, 2500);

// function myStopFunction() {
//  $('#success-alert').hide();
// }

$("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
    $("#success-alert").slideUp(500);
});
    </script>

@endsection

resources/views/pertanyaan/edit.blade.php
@extends('layouts.maindashboard')

@section('content')
<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <!-- Notifikasi menggunakan flash session data -->
                @if (session('success'))
                <div class="alert alert-success" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('success') }}</strong>
                </div>
                @endif

                @if (session('error'))
                <div class="alert alert-error" id="error-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('error') }}</strong>
                </div>
                @endif

                <div class="card border-0 shadow rounded">
                <div class="card-header">
                     <h1 class="card-title"><strong>Form Ubah Pertanyaan</strong></h1>
                    </div>
                    <div class="card-body">
                    
                        <form action="{{ route('pertanyaan.update', $model->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-row">
                            
                            <div class="form-group col-md-4">
                                <label for="pertanyaan">Pertanyaan</label>
                                <input type="text" class="form-control @error('pertanyaan') is-invalid @enderror"
                                    name="pertanyaan" value="{{ old('pertanyaan', $model->pertanyaan) }}" required>

                                <!-- error message untuk title -->
                                @error('pertanyaan')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-4">
                                <label for="variabel">Variabel</label>
                                <input type="text" class="form-control"
                                    name="variabel" value="{{ old('variabel', $model->variabel) }}" >
                            </div>

                            <div class="form-group col-md-4">
                            <label for="id_dimensi">Dimensi</label>
                            <select id="id_dimensi" class="form-control @error('id_dimensi') is-invalid @enderror" name="id_dimensi" value="{{ old('id_dimensi', $model->id_dimensi ) }}" required>
                                <option hidden>Pilih Dimensi</option>
                                @foreach ($dimensis as $dimensi)
                                <option value="{{$dimensi->id}}" {{ $model->id_dimensi == $dimensi->id ? 'selected': '' }}>{{$dimensi->dimensi}}</option>
                                @endforeach
                                
                            </select>
                            <!-- error message untuk title -->
                            @error('id_dimensi')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>


                            <div class="form-group col-md-12">
                                <label for="pila">Pilihan A</label>
                                <input type="text" class="form-control @error('pila') is-invalid @enderror"
                                    name="pila" value="{{ old('pila', $model->pila) }}" required>

                                <!-- error message untuk title -->
                                @error('pila')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-12">
                                <label for="pilb">Pilihan B</label>
                                <input type="text" class="form-control @error('pilb') is-invalid @enderror"
                                    name="pilb" value="{{ old('pilb', $model->pilb) }}" required>

                                <!-- error message untuk title -->
                                @error('pilb')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-12">
                                <label for="pilc">Pilihan C</label>
                                <input type="text" class="form-control @error('pilc') is-invalid @enderror"
                                    name="pilc" value="{{ old('pilc', $model->pilc) }}" required>

                                <!-- error message untuk title -->
                                @error('pilc')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-12">
                                <label for="pild">Pilihan D</label>
                                <input type="text" class="form-control @error('pild') is-invalid @enderror"
                                    name="pild" value="{{ old('pild', $model->pild) }}" required>

                                <!-- error message untuk title -->
                                @error('pild')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>

                            <div class="form-group col-md-12">
                                <label for="pile">Pilihan E</label>
                                <input type="text" class="form-control @error('pile') is-invalid @enderror"
                                    name="pile" value="{{ old('pile', $model->pile) }}" required>

                                <!-- error message untuk title -->
                                @error('pile')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>





                           

                            </div>
                            <button type="submit" class="btn btn-md btn-primary">Save</button>
                            <a href="{{ route('pertanyaan.index') }}" class="btn btn-md btn-secondary">Back</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <script>
        $(document).ready(function() {
  $("#success-alert").hide();
  $("#myWish").click(function showAlert() {
    $("#success-alert").fadeTo(2000, 500).slideUp(500, function() {
      $("#success-alert").slideUp(500);
    });
  });
});
    </script> -->

    <script>
// setTimeout( myStopFunction, 2500);

// function myStopFunction() {
//  $('#success-alert').hide();
// }

$("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
    $("#success-alert").slideUp(500);
});
    </script>

@endsection

resources/views/pertanyaan/pertanyaan.blade.php
@extends('layouts.maindashboard')

@section('content')
<div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <!-- Notifikasi menggunakan flash session data -->

                @if (session('success'))
                <div class="alert alert-success" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('success') }}</strong>
                </div>
                @endif

                @if (session('error'))
                <div class="alert alert-error" id="error-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                    <strong>{{ session('error') }}</strong>
                </div>
                @endif


                <div class="card border-0 shadow rounded">
                <div class="card-header">
                     <h1 class="card-title"><strong>Data Pertanyaan Kuesioner</strong></h1>
                </div>
                    <div class="card-body">
                        <a href="{{url('pertanyaan/create')}}" class="btn btn-md btn-success mb-3 float-right">Tambah Data</a>

                        <table id="role_table" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th scope="col">No</th>
                                    <th scope="col">Pertanyaan</th>
                                    <th scope="col">Dimensi</th>
                                    <th scope="col">Variabel</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($datas as $key=> $data)
                                <tr>
                                    <td>{{ ++$key }}</td>
                                    <td>{{ $data->pertanyaan }}</td>
                                    <td>{{ $data->dimensi }}</td>
                                    <td>{{ $data->variabel }}</td>
                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                                            action="{{ route('pertanyaan.destroy', $data->id) }}" method="POST">
                                            <a href="{{ route('pertanyaan.edit', $data->id) }}    "
                                                class="btn btn-sm btn-primary">Ubah</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">Hapus</button>
                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td class="text-center text-mute" colspan="5">Data post tidak tersedia</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


   

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script> -->

<script>
    $(document).ready(function() {
    $('#role_table').DataTable();
} );
</script>

<script>
// setTimeout( myStopFunction, 2500);

// function myStopFunction() {
//  $('#success-alert').hide();
// }

$("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
    $("#success-alert").slideUp(500);
});
    </script>

    <!-- <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 -->
@endsection