routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\DimensiController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\KuesionerController;
use App\Http\Controllers\PertanyaanController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('pengguna', PenggunaController::class);
Route::resource('dimensi', DimensiController::class);
Route::resource('pertanyaan', PertanyaanController::class);

Route::get('/login', [LoginController::class, 'index'] );
Route::post('/login', [LoginController::class, 'authenticate'] );
Route::post('/logout', [LoginController::class, 'logout'] );

Route::get('/kuesioner', [KuesionerController::class, 'getAllKuesioner'] )->name('kuesioner.kuesioner');
Route::post('/store', [KuesionerController::class, 'store'] )->name('jawaban.store');

Route::get('/dashboard', [LoginController::class, 'afterLogin'] )->name('dashboard.dashboard');

resources/views/layouts/ext-css.blade.php
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <!-- <link rel="stylesheet" href="{{ url('/adminlte/plugins/fontawesome-free/css/all.min.css')}}"> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  
  <!-- Theme style -->
  <link rel="stylesheet" href="{{url('/adminlte/dist/css/adminlte.min.css')}}">
  

resources/views/layouts/ext-js.blade.php
<!-- jQuery -->
<script src="{{ url('/adminlte/plugins/jquery/jquery.min.js')}}"></script>
<script src="{{url('/adminlte/plugins/jquery-knob/jquery.knob.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{url('/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- ChartJS -->
<!-- <script src="{{url('/adminlte/plugins/chart.js/Chart.min.js')}}"></script> -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
<!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
<!-- AdminLTE App -->
<script src="{{url('/adminlte/dist/js/adminlte.min.js')}}"></script>

resources/views/layouts/footerdb.blade.php
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2023 <a href="#">Kuesioner.ai</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

resources/views/layouts/maindashboard.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Kuesioner.ai v1</title>

  @include('layouts.ext-css')
  @include('layouts.ext-js')
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
    @include('layouts.navbardb')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
@include('layouts.sidebardb')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        @yield('content-header')
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      @yield('content')
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

 @include('layouts.footerdb')
</div>
<!-- ./wrapper -->


</body>
</html>

resources/views/layouts/navbardb.blade.php
<nav class="main-header navbar navbar-expand navbar-primary navbar-light" style="background-color: #89C4E1">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <!-- <li class="nav-item d-none d-sm-inline-block">
        <a href="/adminlte/index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li> -->
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      

    <ul class="navbar-nav ms-auto">
      @auth
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
          data-toggle="dropdown" aria-expanded="true">Welcome Back, {{auth()->user()->nama_pengguna}} </a>
          <div class="dropdown-menu">
          <a class="dropdown-item" tabindex="-1" href="#"><i class="nav-icon fas fa-edit"></i> Settings</a>
          <div class="dropdown-divider"></div>
          <form action="/logout" method="post">
            @csrf
            <button type="submit" class="dropdown-item"><i class="nav-icon fas fa-sign-out"></i> Logout</button>
          </form>
          </div>
        </li>
      @endauth
    </ul>
  </nav>

resources/views/layouts/sidebardb.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4" style="background-color: #567189">
    <!-- Brand Logo -->
    <a href="/adminlte/index3.html" class="brand-link">
      <img src="/adminlte/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Kuesioner.ai v1</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <!-- <div class="user-panel mt-3 pb-3 mb-3"> -->
      <div class="form-inline mt-3">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
     
      </div>

      <!-- SidebarSearch Form -->
     

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Main Menu
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
            @if(auth()->user()->hak_akses == 'Administrator')
              <li class="nav-item">
                <a href="{{ route('dashboard.dashboard') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>My Dashboard</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('dimensi.index') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Menu Dimensi</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('pertanyaan.index') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Menu Pertanyaan</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('pengguna.index') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Menu Pengguna</p>
                </a>
              </li>
              @else
              <li class="nav-item">
                <a href="{{ route('dashboard.dashboard') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>My Dashboard</p>
                </a>
              </li>
              @if(!$exists)
              <li class="nav-item">
                <a href="{{ route('kuesioner.kuesioner') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Form Kuesioner</p>
                </a>
              </li>
              @endif
              @endif
            </ul>
          </li>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>